
tickers = {

    "BTCUSDT":"BTC/USD",
    "ETHUSDT":"ETHUSD_PERP",
    "BCHUSDT": "BCH/USD",
    "XRPUSDT": "XRP/USD",
    "EOSUSDT" : "EOS/USDT",
    "LTCUSDT": "LTC/USD",
    "BNBUSDT": "BNB/USD",
    "TRXUSDT": "TRX/USD",
    "ETCUSDT": "ETC/USDT",
    "LINKUSDT": "LINK/USD",
    "DOTUSDT": "DOT/USD",
    "ADAUSDT": "ADA/USD",
    "EOSUSDT": "EOS/USD",
    "TRXUSDT" "TRX/USD"
    "ETCUSDT": "ETC/USD",
    "XLMUSDT":"XLMUSD",
    "ADAUSDT": "ADA/USDT",
    
    "FILEUSDT": "FILEUSD_PERP",
    "EGLDUSDT": "EGLD/USD",
    "DOGEUSDT": "DOGE/USD",
    "UNIUSDT":"UNI/USDT",
    "THETAUSDT": "THETA/USD",

    "SOLUSDT": "SOL/USD",
    "LUNAUSDT": "LUNA/USD",
    "FTMUSDT": "FTM/USD",
    "SANDUSDT": "SAND/USD",
    "MANAUSDT": "MANA/USD",
    "AVAXUSDT": "AVAX/USD",
    "GALAUSDT": "GALAUSD_PERP",
    "MATICUSDT": "MATIC/USD",
    "NEARUSDT": "NEAR/USD",
    "ATOMUSDT": "ATOM/USD",
    "AAVEUSDT":"AAVEUSD_PERP",
    "CRVUSDT": "CRVUSD_PERP",
    "AXSUSDT": "AXSUSD_PERP",
    "ROSEUSDT": "ROSE/USD",
    "XTZUSDT": "XTZ/USD",
    "OPUSDT": "OP/USD",
    }




'''
DASH/USDT
ZEC/USDT
XTZ/USDT
BNB/USDT
ATOM/USDT
ONT/USDT
IOTA/USDT
BAT/USDT
VET/USDT
NEOUSDT
QTUM/USDT
IOST/USDT
THETA/USDT
ALGO/USDT
ZIL/USDT
KNC/USDT
ZRX/USDT
COMP/USDT
OMG/USDT
DOGE/USDT
SXP/USDT
KAVA/USDT
BAND/USDT
RLC/USDT
WAVES/USDT
MKR/USDT
SNX/USDT
DOT/USDT
DEFI/USDT
YFI/USDT
BAL/USDT
CRV/USDT
TRBUSDT
RUNE/USDT
SUSHI/USDT
SRMUSDT
EGLD/USDT
SOL/USDT
ICXUSDT
STORJ/USDT
UNI/USDT
AVAX/USDT
FTM/USDT
HNT/USDT
ENJ/USDT
FLM/USDT
TOMO/USDT
REN/USDT
KSM/USDT
NEAR/USDT
AAVE/USDT
FIL/USDT
RSRUSDT
LRC/USDT
MATIC/USDT
OCEAN/USDT
BELUSDT
CTKUSDT
AXS/USDT
ALPHAUSDT
ZEN/USDT
SKL/USDT
GRT/USDT
BNTUSDT
1INCH/USDT
UNFI/USDT
BTC/BUSD
CHZ/USDT
SAND/USDT
ANKR/USDT
LIT/USDT
REEF/USDT
RVNUSDT
SFPUSDT
XEMUSDT
BTCSTUSDT
COTI/USDT
CHR/USDT
MANA/USDT
ALICE/USDT
HBARUSDT
ONE/USDT
LINA/USDT
STMX/USDT
DENT/USDT
CELR/USDT
HOT/USDT
MTL/USDT
OGN/USDT
NKNUSDT
DGBUSDT
1000SHIB/USDT
BAKEUSDT
GTCUSDT
ETH/BUSD
BTCDOM/USDT
MASK/USDT
BNB/BUSD
ADA/BUSD
DOGEBUSD
XRPBUSD
IOTX/USDT
AUDIO/USDT
C98/USDT
ATA/USDT
SOL/BUSD
DYDX/USDT
1000XEC/USDT
GALA/USDT
CELO/USDT
AR/USDT
KLAY/USDT
ARPA/USDT
CTSIUSDT
LPTUSDT
ENS/USDT
PEOPLE/USDT
ANT/USDT
ROSE/USDT
DUSK/USDT
FLOW/USDT
IMX/USDT
API3/USDT
GMT/USDT
APE/USDT
BNX/USDT
WOO/USDT
JASMY/USDT
DAR/USDT
GAL/USDT
AVAX/BUSD
NEAR/BUSD
GMT/BUSD
APE/BUSD
TRX/BUSD
GALA/BUSD
FTM/BUSD
GAL/BUSD
ANC/BUSD
1000LUNC/BUSD
LUNA2/BUSD
OP/USDT
DOT/BUSD
ICP/BUSD
TLM/BUSD
WAVEBUSD
LINK/BUSD
WAVES/BUSD
XMR/USDT
LTC/BUSD
SAND/BUSD
MATIC/BUSD
CVX/BUSD
FIL/BUSD
LEVER/BUSD
1000SHIB/BUSD
ETC/BUSD
LDO/BUSD
UNI/BUSD
AUCTION/BUSD
INJ/USDT
STG/USDT
SPELL/USDT
1000LUNC/USDT
LUNA2/USDT
AMB/BUSD
PHB/BUSD
LDO/USDT
CVX/USDT
ICP2USDT
FOOTBALL/USDT
APT/USDT
QNT/USDT
APT/BUSD
BLUEBIRD/USDT
'''


tickerscoin = {
    "BTC/USD":"BTC",
    "ETHUSD_PERP":"ETH",
    "LINK/USD": "LINK",
    "BNB/USD": "BNB",
    "TRX/USD": "TRX",
    "DOT/USD": "DOT",
    "ADA/USD": "ADA",
    "EOS/USD": "EOS",
    "LTC/USD": "LTC",
    "BCH/USD": "BCH",
    "XRP/USD": "XRP",
    "ETC/USD": "ETC",
    "FILEUSD_PERP": "FIL",
    "EGLD/USD": "EGLD",
    "DOGE/USD": "DOGE",
    "UNIUSDT": "UNI",
    "THETA/USD": "THETA",
    "XLMUSD": "XLM",
    "SOL/USD": "SOL",
    "LUNA/USD": "LUNA",
    "FTM/USD": "FTM",
    "SAND/USD": "SAND",
    "MANA/USD": "MANA",
    "AVAX/USD": "AVAX",
    "GALAUSD_PERP": "GALA",
    "MATIC/USD": "MATIC",
    "NEAR/USD": "NEAR",
    "ATOM/USD": "ATOm",
    "AAVEUSD_PERP":"AAVE",
    "CRVUSD_PERP": "CRV",
    "AXSUSD_PERP": "AXS",
    "ROSE/USD": "ROSE",
    "XTZ/USD": "XTZ",
    "ICX/USD":  "ICX",
    "ALGO/USD": "ALGO",
    "RUNE/USD": "RUNE",
    "APE/USD":"APE",
    "VET/USD":"VET",
    "ZIL/USD":"ZIL",
    "KNC/USD":"KNC",
    "XMR/USD":"XMR",
    "GMT/USD":"GMT",
    "OP/USD":"OP",
    "ENS/USD":"ENS",
    "CHZ/USD":"CHZ",
    "APT/USD":"APT",
    "OP/USD": "OP",

  }




tickers2coin = {
  "BTC/USD":"BTCUSD_PERP",
  "ETHUSD_PERP": "ETHUSD_PERP",
  "LINK/USD": "LINKUSD_PERP",
  "BNB/USD": "BNBUSD_PERP",
  "TRX/USD": "TRXUSD_PERP",
  "DOT/USD": "DOTUSD_PERP",
  "ADA/USD": "ADAUSD_PERP",
  "EOS/USD": "EOSUSD_PERP",
  "LTC/USD": "LTCUSD_PERP",
  "BCH/USD": "BCHUSD_PERP",
  "XRP/USD": "XRPUSD_PERP",
  "ETC/USD": "ETCUSD_PERP",
  "FILEUSD_PERP": "FILUSD_PERP",
  "EGLD/USD": "EGLDUSD_PERP",
  "DOGE/USD": "DOGEUSD_PERP",
  "UNIUSDT": "UNIUSD_PERP",
  "THETA/USD": "THETAUSD_PERP",
  "XLMUSD": "XLMUSD_PERP",
  "SOL/USD": "SOLUSD_PERP",
  "FTM/USD": "FTMUSD_PERP",
  "SAND/USD": "SANDUSD_PERP",
  "MANA/USD": "MANAUSD_PERP",
  "AVAX/USD": "AVAXUSD_PERP",
  "GALAUSD_PERP": "GALAUSD_PERP",
  "MATIC/USD": "MATICUSD_PERP",
  "NEAR/USD": "NEARUSD_PERP",
  "ATOM/USD": "ATOMUSD_PERP",
  "AAVEUSD_PERP" : "AAVEUSD_PERP",
  "CRVUSD_PERP":"CRVUSD_PERP",
  "AXSUSD_PERP":"AXSUSD_PERP",
  "ROSE/USD": "ROSEUSD_PERP",
  "XTZ/USD": "XTZUSD_PERP",
  "ICX/USD":  "ICXUSD_PERP",
  "ALGO/USD": "ALGOUSD_PERP",
  "RUNE/USD": "RUNEUSD_PERP",
  "APE/USD":"APEUSD_PERP",
  "VET/USD":"VETUSD_PERP",
  "ZIL/USD":"ZILUSD_PERP",
  "KNC/USD":"KNCUSD_PERP",
  "XMR/USD":"XMRUSD_PERP",
  "GMT/USD":"GMTUSD_PERP",
  "OP/USD":"OPUSD_PERP",
  "ENS/USD":"ENSUSD_PERP",
  "CHZ/USD":"CHZUSD_PERP",
  "APT/USD":"APTUSD_PERP",
  "OP/USD":"OPUSD_PERP",
  }